### ISSUE TITLE
apiKey gizlenmeli

### ISSUE THREAD

**Issue by ibrahimatmaca** [Sara-Nefise/MovieApp#3]
https://github.com/Sara-Nefise/MovieApp/blob/7ae86a9d24da3b165c6ef2d8e57830ac76bbb650/lib/core/constant/apiConstants.dart#L8

**Comment by ibrahimatmaca** [comment]
bunun gibi değerleri environment dosyasından çekmeni tavsiye ederim

**Comment by Sara-Nefise** [comment]
bilgilendirme için teşekkürler düzeltiyorum
